#!/usr/bin/env bash

set -xe

TARGET=themecord

echo "#!/usr/bin/env sh" > themecord
echo -e "\n#This is generated by themecord builder!" >> themecord

echo "themecordFiller=\$(cat << 'EOF'" >> themecord
cat ./css/ThemecordFiller.css >> themecord
echo -e "EOF\n)\n" >> themecord

echo "themecordBase=\$(cat << 'EOF'" >> themecord
cat ./css/Themecord.css >> themecord
echo -e "EOF\n)\n" >> themecord

cat ./scripts/themecord.sh >> themecord

chmod +x themecord
