{ pkgs, ... }:

let
  themecordFiller = builtins.readFile ./css/ThemecordFiller.css;
  themecordFiller2 = builtins.readFile ./css/ThemecordFiller2nd.css;

  dark_theme = builtins.readFile ./css/dark_theme.css;
  light_theme = builtins.readFile ./css/light_theme.css;

  themecordBase = builtins.readFile ./css/Themecord.css;
  discordColorsContent = builtins.readFile ./scripts/themecord.sh;

  pywalTemplate = pkgs.writeTextFile {
    name = "pywal-template";
    destination = "~/.config/wal/templates/colors-discord.css";
    text = builtins.readFile ./css/pywal/colors-discord.css;
  };

  wallustConfig = pkgs.writeTextFile {
    name = "wallust-config";
    destination = "~/.config/wallust/wallust.toml";
    text = builtins.readFile ./css/wallust/wallust.toml;
  };

  wallustTemplate = pkgs.writeTextFile {
    name = "wallust-template";
    destination = "~/.config/wallust/templates/colors-discord.css";
    text = builtins.readFile ./css/wallust/colors-discord.css;
  };

in
  pkgs.writeScriptBin "themecord" ''
    #!/usr/bin/env bash

    # Generated by nix
    themecordFiller=$(cat << 'EOF'
    ${themecordFiller}
    EOF
    )
    themecordFiller2=$(cat << 'EOF'
    ${themecordFiller2}
    EOF
    )
    dark_theme=$(cat << 'EOF'
    ${dark_theme}
    EOF
    )
    light_theme=$(cat << 'EOF'
    ${light_theme}
    EOF
    )
    themecordBase=$(cat << 'EOF'
    ${themecordBase}
    EOF
    )
    ${discordColorsContent}
  ''

