#!/bin/bash

yay -S --noconfirm vencord-installer-cli python-pywal swww

cp colors-discord.css ~/.config/wal/templates/

mkdir ~/.config/themecord

sudo vencordinstallercli -install
cp ./Themecord.css /home/$USER/.config/Vencord/themes/
cp ./ThemecordFiller.css.themecord /home/$USER/.config/Vencord/themes/
cp ./discordColors.sh  ~/.config/themecord
cp ./update_wallpaper.sh ~/.config/themecord
