#!/bin/bash

echo "Are you sure, you want uninstall Themecord?(y/n): "

read choice

if [ "$choice" ==  "y" ] || [ "$choice" ==  "Y" ]; then
  rm ~/.config/Vencord/themes/Themecord*
else
  exit 1
fi

if [ $? -eq 0 ]; then
    echo "Themecord uninstalled successfully"
else
    echo "Failed"
fi

